# Generated by Django 5.2.8 on 2025-12-13 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField()),
                ('career_page', models.URLField(blank=True, null=True)),
                ('source', models.CharField(default='Google Jobs', max_length=50)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('latex_code', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('altered_code', models.TextField(blank=True)),
                ('final_resume_file', models.FileField(blank=True, null=True, upload_to='final_resumes/')),
                ('hr_name', models.CharField(blank=True, max_length=100)),
                ('hr_email', models.EmailField(blank=True, max_length=254)),
                ('email_body', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobhunter.jobpost')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobhunter.resume')),
            ],
        ),
    ]
