# Generated by Django 5.2.8 on 2025-12-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.TextField(),
        ),
    ]
