# Generated by Django 5.2.8 on 2025-12-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunter', '0002_alter_jobpost_company_alter_jobpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='career_page',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
