# Generated by Django 5.1 on 2025-12-24 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunter', '0004_interviewsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='email_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='hr_email_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('human_required', 'Requires Human Verification')], default='unverified', max_length=20),
        ),
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('gathering', 'Gathering Jobs'), ('waiting_approval', 'Waiting for Human Approval'), ('approved', 'Approved'), ('completed', 'Sent'), ('cancelled', 'Cancelled')], default='gathering', max_length=20)),
                ('approval_email_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_subject', models.CharField(max_length=255)),
                ('proposed_body', models.TextField()),
                ('alt_subject', models.CharField(blank=True, max_length=255)),
                ('alt_body', models.TextField(blank=True)),
                ('tailored_resume', models.FileField(upload_to='outreach_resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent to HR')], default='pending', max_length=20)),
                ('user_feedback', models.TextField(blank=True, help_text='Edit instructions from email reply')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobhunter.jobpost')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='jobhunter.outreachcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('current_status', models.CharField(help_text='e.g. Student, Fresher, Experience + years', max_length=100)),
                ('skills', models.TextField(help_text='Comma separated skills')),
                ('portfolio_links', models.TextField(blank=True, help_text='One per line')),
                ('availability', models.CharField(default='Immediate', max_length=100)),
                ('base_resume_file', models.FileField(blank=True, null=True, upload_to='base_resumes/')),
                ('base_resume_text', models.TextField(help_text='Plain text version for AI processing')),
                ('projects', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
